version: '3.8'
services:
  jekyll:
    build: .  # 👈 Build the image using our Dockerfile
    container_name: my-jekyll-site
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
    command: jekyll serve --host 0.0.0.0
